# Generated by Django 5.2.14 on 2026-05-30 10:57

import django.db.models.deletion
import django.utils.timezone
import messenger.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('encode', 'Encode Operation'), ('decode', 'Decode Operation'), ('key_generated', 'Key Generated'), ('failed_decrypt', 'Failed Decryption'), ('invalid_upload', 'Invalid Upload')], max_length=24)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StegOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('encode', 'Encode'), ('decode', 'Decode')], max_length=8)),
                ('operation_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('source_image', models.ImageField(blank=True, null=True, upload_to=messenger.models.source_image_upload_path)),
                ('stego_image', models.ImageField(blank=True, null=True, upload_to=messenger.models.stego_image_upload_path)),
                ('encrypted_payload', models.TextField(blank=True)),
                ('encryption_method', models.CharField(default='Fernet', max_length=32)),
                ('message_length', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(blank=True, max_length=64, unique=True)),
                ('node_status', models.CharField(choices=[('secure', 'Secure'), ('warning', 'Warning'), ('offline', 'Offline')], default='secure', max_length=16)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('session_timeout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
